repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4  # Use the ref you want to point at
    hooks:
      - id: flake8
        args: ['--count', '--show-source', '--statistics', '--max-complexity=10', '--max-line-length=127', '--ignore=W503,W504,W293,W391,E127,E101,W191,E126,E117,E128,E122,E131']
        exclude: ^amos/(mts/|gui/(utils|models|detect.py)|crawler/collect_links.py)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

# workflow:
# - pip install pre-commit
# - pre-commit install # to install the .pre-commit-config.yaml as pre-commit hook
