# COCO 2017 dataset http://cocodataset.org - first 128 training images
# Train command: python train.py --data berlin_sights_config.yaml
# Default dataset location is next to /yolov3:
#   /parent_folder
#     /coco128
#     /yolov3


# download command/URL (optional)
#download: https://github.com/ultralytics/yolov5/releases/download/v1.0/coco128.zip

# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
train: [../training_data/brandenburger_tor/images/,../training_data/fernsehturm/images/,../training_data/siegessaeule/images/]  # 128 images
val: [../training_data/brandenburger_tor/images/,../training_data/fernsehturm/images/,../training_data/siegessaeule/images/]  # 128 images

# number of classes
nc: 3

# class names
names: [ 'brandenburger_tor',
         'fernsehturm',
         'siegessaeule' ]
