# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Code Testing

on:
  push:
    branches: [main, develop, feature/64-fix_ci_pipeline]
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest mock pytest-cov
          for entry in ./amos/*; do
            touch requirements.txt
            if [ -f $entry/requirements.txt ]; then
              cat $entry/requirements.txt >> requirements.txt;
            fi
          done
          pip install -r requirements.txt;
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --ignore=W503,W504,W293,W391,E127 --exclude=amos/mts,amos/crawler/collect_links.py
      - name: Test with pytest
        run: |
          pytest || true
      - name: Test Code Coverage
        run: |
          for entry in ./amos/*; do
            result=$(pytest $entry || true --cov=$entry);
            echo -e "$result\n";
            percentage=$(echo $result | grep "TOTAL" | awk ' {print $4}' | sed 's/%$//');
            percentage=$(percentage)*100
            echo -e "$percentage\n"
            if [[ $percentage -lt 70 ]]; then
              echo -e "Current code coverage for $entry is under 70%\n";
            fi
          done
