# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Code Testing

on:
  push:
    branches: [main, develop, feature/50-rework_ci]
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest mock pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest

      - name: Test Code Coverage
        run: |
          for entry in ./amos/*; do
            result=$(pytest --cov=$entry);
            echo $result;
            percentage=$(echo $result | grep "TOTAL" | awk ' {print $4}' | sed 's/%$//');
            echo $percentage
            if [[ "$percentage" -lt 70 ]]; then
              echo "Current code coverage for $entry is under 70%";
              exit 1;
            fi
          done
